apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulsar-console

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - api-deployment.yaml
  - frontend-deployment.yaml
  - worker-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.0.2"
